name:                mcmc
version:             0.1.0.0
github:              "dschrempf/mcmc"
license:             BSD3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Sample from a posterior using Markov chain Monte Carlo
category:            Math, Statistics
description:         Please see the README on GitHub at <https://github.com/dschrempf/mcmc#readme>

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - array
    - base >= 4.7 && < 5
    - containers
    - log-domain
    - microlens
    - mwc-random
    - statistics
    - text
    - transformers

benchmarks:
  mcmc-bench:
    main:        Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - log-domain
      - mcmc
      - microlens
      - mwc-random
      - statistics
      - text
      - vector

tests:
  mcmc-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - hspec
      - hspec-discover
      - mcmc
      - QuickCheck

executables:
  archery:
    main:        Archery.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - log-domain
      - mcmc
      - mwc-random
      - statistics
      - text
