#+bibliography: ~/Evolutionary-Biology/Bibliography/bibliography.bib
#+cite_export: basic

* Markov chain Monte Carlo sampler
#+html: <p align="center"><img src="https://travis-ci.org/dschrempf/mcmc.svg?branch=master"/></p>

Sample from a posterior using Markov chain Monte Carlo (MCMC) algorithms.

At the moment, the following algorithms are available:
- Metropolis-Hastings-Green [cite:@Geyer2011];
- Metropolis-coupled Markov chain Monte Carlo (also known as parallel
  tempering) [cite:@Geyer1991; @Altekar2004];
- Hamilton Monte Carlo proposal [cite:@Neal2011];
- No U-Turn Sampler (NUTS) [cite:@Hoffman2014].

** Documentation
The [[https://hackage.haskell.org/package/mcmc/docs/Mcmc.html][source code]] contains detailed documentation about general concepts as well
as specific functions.

** Examples
The Git repository also includes [[https://github.com/dschrempf/mcmc/tree/master/mcmc-examples][example MCMC analyses]]. Build them with
[[https://cabal.readthedocs.io/en/latest/cabal-commands.html#][cabal-install]] or [[https://docs.haskellstack.org/en/stable/README/][Stack]].

#+name: Build
#+begin_src sh :exports code :results none
git clone https://github.com/dschrempf/mcmc.git
cd mcmc
stack build
#+end_src

For example, estimate the [[https://github.com/dschrempf/mcmc/blob/master/mcmc-examples/Archery/Archery.hs][accuracy of an archer]] with
#+name: Archery
#+begin_src sh :exports code :results none
stack exec archery
#+end_src

For a more involved example, have a look at a [[https://github.com/dschrempf/mcmc-dating][phylogenetic dating project]].

** Ideas                                                             :noexport:
*** Marginal likelihood
E.g., stepping stone (see RevBayes).

*** Proposals on tree topologies.
- NNI.
- Narrow. What is this? See RevBayes.
- FNPR (same here).

General questions: How do we handle changing topologies? Then, the node paths
change, and everything is messed up.


* References
#+print_bibliography:
