* Markov chain Monte Carlo sampler
#+html: <p align="center"><img src="https://travis-ci.org/dschrempf/mcmc.svg?branch=master"/></p>

Sample from a posterior using Markov chain Monte Carlo (MCMC) algorithms.

At the moment, the following algorithms are available:
- Metropolis-Hastings-Green [fn:1];
- Metropolis-coupled Markov chain Monte Carlo (also known as parallel
  tempering) [fn:2] [fn:3].
- Hamilton Monte Carlo proposal [fn:4].

** Documentation
The [[https://hackage.haskell.org/package/mcmc/docs/Mcmc.html][source code]] contains detailed documentation about general concepts as well
as specific functions.

** Examples
The Git repository also includes [[https://github.com/dschrempf/mcmc/tree/master/mcmc-examples][example MCMC analyses]]. Build them with
[[https://cabal.readthedocs.io/en/latest/cabal-commands.html#][cabal-install]] or [[https://docs.haskellstack.org/en/stable/README/][Stack]].

#+name: Build
#+begin_src sh :exports code :results none
git clone https://github.com/dschrempf/mcmc.git
cd mcmc
stack build
#+end_src

For example, estimate the [[https://github.com/dschrempf/mcmc/blob/master/mcmc-examples/Archery/Archery.hs][accuracy of an archer]] with
#+name: Archery
#+begin_src sh :exports code :results none
stack exec archery
#+end_src

For a more involved example, have a look at a [[https://github.com/dschrempf/mcmc-dating][phylogenetic dating project]].

** Ideas                                                             :noexport:
*** Marginal likelihood
E.g., stepping stone (see RevBayes).

*** Proposals on tree topologies.
- NNI.
- Narrow. What is this? See RevBayes.
- FNPR (same here).

General questions: How do we handle changing topologies? Then, the node paths
change, and everything is messed up.

* Footnotes
[fn:4] Neal, R. M., Mcmc Using Hamiltonian Dynamics, In S. Brooks, A. Gelman, G.
Jones, & X. Meng (Eds.), Handbook of Markov Chain Monte Carlo (2011). CRC press.

[fn:3] Altekar, G., Dwarkadas, S., Huelsenbeck, J. P., & Ronquist, F., Parallel
metropolis coupled markov chain monte carlo for bayesian phylogenetic inference,
Bioinformatics, 20(3), 407–415 (2004).

[fn:2] Geyer, C. J., Markov chain monte carlo maximum likelihood, Computing
Science and Statistics, Proceedings of the 23rd Symposium on the Interface,
(1991).

[fn:1] Geyer, C. J., Introduction to Markov chain Monte Carlo, In Handbook of
Markov Chain Monte Carlo (pp. 45) (2011). CRC press.
