resolver: lts-18.8

packages:
  - ./mcmc
  - ./mcmc-examples
  - ./mcmc-statistics

extra-deps:
  # - circular-0.4.0.0
  # - dirichlet-0.1.0.4
  - ../circular
  - ../dirichlet

# # LLVM.
# ghc-options: {"$everything": -O2 -fllvm}

nix:
  add-gc-roots: true
  packages:
    - zlib
