resolver: nightly-2022-02-27

packages:
  - ./mcmc
  - ./mcmc-examples
  - ./mcmc-statistics

extra-deps:
  # - circular-0.4.0.0
  # - dirichlet-0.1.0.4
  - ../circular
  - ../dirichlet
  - ../covariance

# # LLVM.
# ghc-options: {"$everything": -O2 -fllvm}
