resolver: nightly-2022-07-10

packages:
  - ./mcmc
  - ./mcmc-examples
  - ./mcmc-statistics

extra-deps:
  #- ../circular
  #- ../dirichlet
  #- ../covariance

# # LLVM.
# ghc-options: {"$everything": -O2 -fllvm}
