resolver: lts-18.8

packages:
  - ./mcmc
  - ./mcmc-examples
  - ./mcmc-statistics

extra-deps:
  # - circular-0.4.0.0
  # - dirichlet-0.1.0.4
  - ../circular
  - ../dirichlet
  - ../covariance
  - glasso-0.1.0@sha256:abf1b0cb0b9cc8c106f833a2549e2be95111a58296d6cc01c39e18c03abef797,930

# # LLVM.
# ghc-options: {"$everything": -O2 -fllvm}
