name:                mcmc-examples
version:             0.1.3
github:              "dschrempf/mcmc"
license:             GPL-3.0-or-later
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Markov chain Monte Carlo examples using the `mcmc` library
category:            Math, Statistics
description:         Please see the README on GitHub at <https://github.com/dschrempf/mcmc#readme>

ghc-options:
  - -Wall

executables:
  archery:
    main:        Archery.hs
    source-dirs: Archery
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - base >= 4.7 && < 5
      - log-domain
      - mcmc
      - mwc-random
      - statistics
      - text
    generated-other-modules: Paths_mcmc_examples
  approx-plh:
    main:        ApproximatePhylogeneticLikelihood.hs
    source-dirs: ApproximatePhylogeneticLikelihood
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - algebraic-graphs
      - base >= 4.7 && < 5
      - log-domain
      - mcmc
      - microlens
      - mwc-random
      - statistics
      - text
    generated-other-modules: Paths_mcmc_examples
