name:                mcmc-statistics
version:             0.1.3
github:              "dschrempf/mcmc"
license:             GPL-3.0-or-later
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Analyze Markov chain Monte Carlo runs
category:            Math, Statistics
description:         Please see the README on GitHub at <https://github.com/dschrempf/mcmc#readme>

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - pava
    - statistics
    - vector
  generated-other-modules: Paths_mcmc_statistics

# tests:
#   mcmc-test:
#     main:        Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - base >= 4.7 && < 5
#       - hspec
#       - hspec-discover
#       - mcmc-statistics
#       - vector
