name:                mcmc
version:             0.2.0
github:              "dschrempf/mcmc"
license:             GPL-3.0-or-later
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Sample from a posterior using Markov chain Monte Carlo
category:            Math, Statistics
description:         Please see the README on GitHub at <https://github.com/dschrempf/mcmc#readme>

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - data-default
    - directory
    - double-conversion
    - log-domain
    - microlens
    - mwc-random
    - statistics
    - time
    - transformers
    - vector
    - zlib
  generated-other-modules: Paths_mcmc

benchmarks:
  mcmc-bench:
    main:        Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - log-domain
      - mcmc
      - microlens
      - mwc-random
      - statistics
      - vector

tests:
  mcmc-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - directory
      - hspec
      - hspec-discover
      - log-domain
      - mcmc
      - mwc-random
      - statistics
      - QuickCheck
      - vector
